/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ResumeMatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_EXPERIENCE"
      | "MAX_SKILL_SCORE"
      | "SKILL_VECTOR_SIZE"
      | "computeMatchScore"
      | "confidentialProtocolId"
      | "getMatchScore"
      | "hasJobRequirement"
      | "hasMatchResult"
      | "hasProfile"
      | "jobRequirements"
      | "matchResults"
      | "profiles"
      | "submitEncryptedProfile"
      | "submitJobRequirement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobRequirementSubmitted"
      | "MatchComputed"
      | "ProfileSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_EXPERIENCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SKILL_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SKILL_VECTOR_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeMatchScore",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchScore",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasJobRequirement",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMatchResult",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobRequirements",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchResults",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedProfile",
    values: [BytesLike[], BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitJobRequirement",
    values: [BytesLike[], BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_EXPERIENCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SKILL_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SKILL_VECTOR_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeMatchScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasJobRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jobRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitJobRequirement",
    data: BytesLike
  ): Result;
}

export namespace JobRequirementSubmittedEvent {
  export type InputTuple = [employer: AddressLike];
  export type OutputTuple = [employer: string];
  export interface OutputObject {
    employer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchComputedEvent {
  export type InputTuple = [profileOwner: AddressLike, employer: AddressLike];
  export type OutputTuple = [profileOwner: string, employer: string];
  export interface OutputObject {
    profileOwner: string;
    employer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileSubmittedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ResumeMatch extends BaseContract {
  connect(runner?: ContractRunner | null): ResumeMatch;
  waitForDeployment(): Promise<this>;

  interface: ResumeMatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_EXPERIENCE: TypedContractMethod<[], [bigint], "view">;

  MAX_SKILL_SCORE: TypedContractMethod<[], [bigint], "view">;

  SKILL_VECTOR_SIZE: TypedContractMethod<[], [bigint], "view">;

  computeMatchScore: TypedContractMethod<
    [profileOwner: AddressLike, employer: AddressLike],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMatchScore: TypedContractMethod<
    [profileOwner: AddressLike, employer: AddressLike],
    [string],
    "view"
  >;

  hasJobRequirement: TypedContractMethod<
    [employer: AddressLike],
    [boolean],
    "view"
  >;

  hasMatchResult: TypedContractMethod<
    [profileOwner: AddressLike, employer: AddressLike],
    [boolean],
    "view"
  >;

  hasProfile: TypedContractMethod<[owner: AddressLike], [boolean], "view">;

  jobRequirements: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        minExperience: string;
        softSkillWeight: string;
        employer: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  matchResults: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, string, boolean] & {
        score: string;
        profileOwner: string;
        employer: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        experience: string;
        softSkills: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  submitEncryptedProfile: TypedContractMethod<
    [
      encryptedSkills: BytesLike[],
      encryptedExperience: BytesLike,
      encryptedSoftSkills: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitJobRequirement: TypedContractMethod<
    [
      encryptedSkillWeights: BytesLike[],
      encryptedMinExperience: BytesLike,
      encryptedSoftSkillWeight: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_EXPERIENCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SKILL_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SKILL_VECTOR_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeMatchScore"
  ): TypedContractMethod<
    [profileOwner: AddressLike, employer: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMatchScore"
  ): TypedContractMethod<
    [profileOwner: AddressLike, employer: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasJobRequirement"
  ): TypedContractMethod<[employer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasMatchResult"
  ): TypedContractMethod<
    [profileOwner: AddressLike, employer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobRequirements"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        minExperience: string;
        softSkillWeight: string;
        employer: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchResults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, string, boolean] & {
        score: string;
        profileOwner: string;
        employer: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        experience: string;
        softSkills: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitEncryptedProfile"
  ): TypedContractMethod<
    [
      encryptedSkills: BytesLike[],
      encryptedExperience: BytesLike,
      encryptedSoftSkills: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitJobRequirement"
  ): TypedContractMethod<
    [
      encryptedSkillWeights: BytesLike[],
      encryptedMinExperience: BytesLike,
      encryptedSoftSkillWeight: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "JobRequirementSubmitted"
  ): TypedContractEvent<
    JobRequirementSubmittedEvent.InputTuple,
    JobRequirementSubmittedEvent.OutputTuple,
    JobRequirementSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MatchComputed"
  ): TypedContractEvent<
    MatchComputedEvent.InputTuple,
    MatchComputedEvent.OutputTuple,
    MatchComputedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileSubmitted"
  ): TypedContractEvent<
    ProfileSubmittedEvent.InputTuple,
    ProfileSubmittedEvent.OutputTuple,
    ProfileSubmittedEvent.OutputObject
  >;

  filters: {
    "JobRequirementSubmitted(address)": TypedContractEvent<
      JobRequirementSubmittedEvent.InputTuple,
      JobRequirementSubmittedEvent.OutputTuple,
      JobRequirementSubmittedEvent.OutputObject
    >;
    JobRequirementSubmitted: TypedContractEvent<
      JobRequirementSubmittedEvent.InputTuple,
      JobRequirementSubmittedEvent.OutputTuple,
      JobRequirementSubmittedEvent.OutputObject
    >;

    "MatchComputed(address,address)": TypedContractEvent<
      MatchComputedEvent.InputTuple,
      MatchComputedEvent.OutputTuple,
      MatchComputedEvent.OutputObject
    >;
    MatchComputed: TypedContractEvent<
      MatchComputedEvent.InputTuple,
      MatchComputedEvent.OutputTuple,
      MatchComputedEvent.OutputObject
    >;

    "ProfileSubmitted(address)": TypedContractEvent<
      ProfileSubmittedEvent.InputTuple,
      ProfileSubmittedEvent.OutputTuple,
      ProfileSubmittedEvent.OutputObject
    >;
    ProfileSubmitted: TypedContractEvent<
      ProfileSubmittedEvent.InputTuple,
      ProfileSubmittedEvent.OutputTuple,
      ProfileSubmittedEvent.OutputObject
    >;
  };
}
